baseURL: 'https://naurosromim.github.io'
languageCode: 'en'
title: 'Thinking clearly 🧐'
defaultContentLanguage: 'en'
enableRobotsTXT: true

publishDir: "docs"

params:
  description: "To write well is to think clearly"
  author: "Syed Nauros Hossain Romim"

  facebook: '#'
  youtube: '#'