baseURL: 'https://example.com'
languageCode: 'en'
title: 'Thinking clearly 🧐'
defaultContentLanguage: 'en'
enableRobotsTXT: true

params:
  description: "To write well is to think clearly"
  author: "Syed Nauros Hossain Romim"

  facebook: '#'
  youtube: '#'